//
//The math over grpc api definition

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: mapi/mapi.proto

package math_over_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// supported operaions
type Opcode int32

const (
	Opcode_NOP Opcode = 0
	Opcode_ADD Opcode = 1
	Opcode_SUB Opcode = 2
	Opcode_MUL Opcode = 3
	Opcode_DIV Opcode = 4
)

// Enum value maps for Opcode.
var (
	Opcode_name = map[int32]string{
		0: "NOP",
		1: "ADD",
		2: "SUB",
		3: "MUL",
		4: "DIV",
	}
	Opcode_value = map[string]int32{
		"NOP": 0,
		"ADD": 1,
		"SUB": 2,
		"MUL": 3,
		"DIV": 4,
	}
)

func (x Opcode) Enum() *Opcode {
	p := new(Opcode)
	*p = x
	return p
}

func (x Opcode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Opcode) Descriptor() protoreflect.EnumDescriptor {
	return file_mapi_mapi_proto_enumTypes[0].Descriptor()
}

func (Opcode) Type() protoreflect.EnumType {
	return &file_mapi_mapi_proto_enumTypes[0]
}

func (x Opcode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Opcode.Descriptor instead.
func (Opcode) EnumDescriptor() ([]byte, []int) {
	return file_mapi_mapi_proto_rawDescGZIP(), []int{0}
}

// the request needs the type of operation and the operands
type OpRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Op     Opcode `protobuf:"varint,1,opt,name=Op,proto3,enum=math_over_grpc.Opcode" json:"Op,omitempty"`
	Unary  string `protobuf:"bytes,2,opt,name=Unary,proto3" json:"Unary,omitempty"`
	Binary string `protobuf:"bytes,3,opt,name=Binary,proto3" json:"Binary,omitempty"`
}

func (x *OpRequest) Reset() {
	*x = OpRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapi_mapi_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpRequest) ProtoMessage() {}

func (x *OpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mapi_mapi_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpRequest.ProtoReflect.Descriptor instead.
func (*OpRequest) Descriptor() ([]byte, []int) {
	return file_mapi_mapi_proto_rawDescGZIP(), []int{0}
}

func (x *OpRequest) GetOp() Opcode {
	if x != nil {
		return x.Op
	}
	return Opcode_NOP
}

func (x *OpRequest) GetUnary() string {
	if x != nil {
		return x.Unary
	}
	return ""
}

func (x *OpRequest) GetBinary() string {
	if x != nil {
		return x.Binary
	}
	return ""
}

// response only returns the result
type OpResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=Result,proto3" json:"Result,omitempty"`
}

func (x *OpResponse) Reset() {
	*x = OpResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapi_mapi_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpResponse) ProtoMessage() {}

func (x *OpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mapi_mapi_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpResponse.ProtoReflect.Descriptor instead.
func (*OpResponse) Descriptor() ([]byte, []int) {
	return file_mapi_mapi_proto_rawDescGZIP(), []int{1}
}

func (x *OpResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_mapi_mapi_proto protoreflect.FileDescriptor

var file_mapi_mapi_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6d, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0e, 0x6d, 0x61, 0x74, 0x68, 0x5f, 0x6f, 0x76, 0x65, 0x72, 0x5f, 0x67, 0x72, 0x70,
	0x63, 0x22, 0x61, 0x0a, 0x09, 0x4f, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26,
	0x0a, 0x02, 0x4f, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x6d, 0x61, 0x74,
	0x68, 0x5f, 0x6f, 0x76, 0x65, 0x72, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4f, 0x70, 0x63, 0x6f,
	0x64, 0x65, 0x52, 0x02, 0x4f, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x55, 0x6e, 0x61, 0x72, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x55, 0x6e, 0x61, 0x72, 0x79, 0x12, 0x16, 0x0a, 0x06,
	0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x42, 0x69,
	0x6e, 0x61, 0x72, 0x79, 0x22, 0x24, 0x0a, 0x0a, 0x4f, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2a, 0x35, 0x0a, 0x06, 0x4f, 0x70,
	0x63, 0x6f, 0x64, 0x65, 0x12, 0x07, 0x0a, 0x03, 0x4e, 0x4f, 0x50, 0x10, 0x00, 0x12, 0x07, 0x0a,
	0x03, 0x41, 0x44, 0x44, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x53, 0x55, 0x42, 0x10, 0x02, 0x12,
	0x07, 0x0a, 0x03, 0x4d, 0x55, 0x4c, 0x10, 0x03, 0x12, 0x07, 0x0a, 0x03, 0x44, 0x49, 0x56, 0x10,
	0x04, 0x32, 0x56, 0x0a, 0x0c, 0x4d, 0x61, 0x74, 0x68, 0x4f, 0x76, 0x65, 0x72, 0x47, 0x72, 0x70,
	0x63, 0x12, 0x46, 0x0a, 0x0b, 0x44, 0x6f, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x19, 0x2e, 0x6d, 0x61, 0x74, 0x68, 0x5f, 0x6f, 0x76, 0x65, 0x72, 0x5f, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x4f, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x6d, 0x61,
	0x74, 0x68, 0x5f, 0x6f, 0x76, 0x65, 0x72, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4f, 0x70, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x24, 0x5a, 0x22, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x61, 0x79, 0x61, 0x73, 0x33, 0x36, 0x30,
	0x2f, 0x6d, 0x61, 0x74, 0x68, 0x5f, 0x6f, 0x76, 0x65, 0x72, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mapi_mapi_proto_rawDescOnce sync.Once
	file_mapi_mapi_proto_rawDescData = file_mapi_mapi_proto_rawDesc
)

func file_mapi_mapi_proto_rawDescGZIP() []byte {
	file_mapi_mapi_proto_rawDescOnce.Do(func() {
		file_mapi_mapi_proto_rawDescData = protoimpl.X.CompressGZIP(file_mapi_mapi_proto_rawDescData)
	})
	return file_mapi_mapi_proto_rawDescData
}

var file_mapi_mapi_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_mapi_mapi_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_mapi_mapi_proto_goTypes = []interface{}{
	(Opcode)(0),        // 0: math_over_grpc.Opcode
	(*OpRequest)(nil),  // 1: math_over_grpc.OpRequest
	(*OpResponse)(nil), // 2: math_over_grpc.OpResponse
}
var file_mapi_mapi_proto_depIdxs = []int32{
	0, // 0: math_over_grpc.OpRequest.Op:type_name -> math_over_grpc.Opcode
	1, // 1: math_over_grpc.MathOverGrpc.DoOperation:input_type -> math_over_grpc.OpRequest
	2, // 2: math_over_grpc.MathOverGrpc.DoOperation:output_type -> math_over_grpc.OpResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_mapi_mapi_proto_init() }
func file_mapi_mapi_proto_init() {
	if File_mapi_mapi_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mapi_mapi_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mapi_mapi_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mapi_mapi_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mapi_mapi_proto_goTypes,
		DependencyIndexes: file_mapi_mapi_proto_depIdxs,
		EnumInfos:         file_mapi_mapi_proto_enumTypes,
		MessageInfos:      file_mapi_mapi_proto_msgTypes,
	}.Build()
	File_mapi_mapi_proto = out.File
	file_mapi_mapi_proto_rawDesc = nil
	file_mapi_mapi_proto_goTypes = nil
	file_mapi_mapi_proto_depIdxs = nil
}
